--
-- PostgreSQL database dump
--

\restrict TIBdmojoX5r7fybLtgNbVozTi7mzDFlkbHCw7SO2uGEIBbr5W9URLV61LcU6wKJ

-- Dumped from database version 14.23
-- Dumped by pg_dump version 14.23

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: appointment; Type: TABLE; Schema: public; Owner: sandrine
--

CREATE TABLE public.appointment (
    id uuid NOT NULL,
    date_time timestamp(0) without time zone NOT NULL,
    status character varying(50) NOT NULL,
    patient_id uuid NOT NULL,
    treatment_id uuid
);


ALTER TABLE public.appointment OWNER TO sandrine;

--
-- Name: article; Type: TABLE; Schema: public; Owner: sandrine
--

CREATE TABLE public.article (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    content text NOT NULL,
    category character varying(50) NOT NULL,
    author_name character varying(255) NOT NULL,
    image_path character varying(255) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone NOT NULL,
    is_published boolean NOT NULL,
    author_id uuid NOT NULL
);


ALTER TABLE public.article OWNER TO sandrine;

--
-- Name: article_id_seq; Type: SEQUENCE; Schema: public; Owner: sandrine
--

ALTER TABLE public.article ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: sandrine
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO sandrine;

--
-- Name: gift_card; Type: TABLE; Schema: public; Owner: sandrine
--

CREATE TABLE public.gift_card (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    amount numeric(10,2) NOT NULL,
    recipient_name character varying(255) NOT NULL,
    message text,
    is_used boolean NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    expires_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    si_digital boolean NOT NULL,
    purchaser_id uuid NOT NULL,
    treatment_id uuid
);


ALTER TABLE public.gift_card OWNER TO sandrine;

--
-- Name: gift_card_id_seq; Type: SEQUENCE; Schema: public; Owner: sandrine
--

ALTER TABLE public.gift_card ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gift_card_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lexicon; Type: TABLE; Schema: public; Owner: sandrine
--

CREATE TABLE public.lexicon (
    id integer NOT NULL,
    term character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    definition text NOT NULL,
    author_id uuid NOT NULL
);


ALTER TABLE public.lexicon OWNER TO sandrine;

--
-- Name: lexicon_id_seq; Type: SEQUENCE; Schema: public; Owner: sandrine
--

ALTER TABLE public.lexicon ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lexicon_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: sandrine
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


ALTER TABLE public.messenger_messages OWNER TO sandrine;

--
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: sandrine
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment; Type: TABLE; Schema: public; Owner: sandrine
--

CREATE TABLE public.payment (
    id integer NOT NULL,
    amount numeric(10,2) NOT NULL,
    stripe_id character varying(255) DEFAULT NULL::character varying,
    status character varying(50) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    payer_id uuid NOT NULL
);


ALTER TABLE public.payment OWNER TO sandrine;

--
-- Name: payment_id_seq; Type: SEQUENCE; Schema: public; Owner: sandrine
--

ALTER TABLE public.payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reset_password_request; Type: TABLE; Schema: public; Owner: sandrine
--

CREATE TABLE public.reset_password_request (
    id integer NOT NULL,
    selector character varying(20) NOT NULL,
    hashed_token character varying(100) NOT NULL,
    requested_at timestamp(0) without time zone NOT NULL,
    expires_at timestamp(0) without time zone NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.reset_password_request OWNER TO sandrine;

--
-- Name: reset_password_request_id_seq; Type: SEQUENCE; Schema: public; Owner: sandrine
--

ALTER TABLE public.reset_password_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reset_password_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: therapeutic_exchange; Type: TABLE; Schema: public; Owner: sandrine
--

CREATE TABLE public.therapeutic_exchange (
    id integer NOT NULL,
    subject character varying(255) NOT NULL,
    message text NOT NULL,
    status character varying(50) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    patient_id uuid NOT NULL
);


ALTER TABLE public.therapeutic_exchange OWNER TO sandrine;

--
-- Name: therapeutic_exchange_id_seq; Type: SEQUENCE; Schema: public; Owner: sandrine
--

ALTER TABLE public.therapeutic_exchange ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.therapeutic_exchange_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: treatment; Type: TABLE; Schema: public; Owner: sandrine
--

CREATE TABLE public.treatment (
    id uuid NOT NULL,
    title character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    duration integer NOT NULL,
    price numeric(10,2) NOT NULL,
    protocol_benefits text NOT NULL,
    type character varying(50) NOT NULL,
    image_path character varying(255) DEFAULT NULL::character varying,
    is_active boolean NOT NULL
);


ALTER TABLE public.treatment OWNER TO sandrine;

--
-- Name: user; Type: TABLE; Schema: public; Owner: sandrine
--

CREATE TABLE public."user" (
    id uuid NOT NULL,
    email character varying(180) NOT NULL,
    roles json NOT NULL,
    password character varying(255) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    wallet numeric(10,2) NOT NULL
);


ALTER TABLE public."user" OWNER TO sandrine;

--
-- Name: appointment appointment_pkey; Type: CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.appointment
    ADD CONSTRAINT appointment_pkey PRIMARY KEY (id);


--
-- Name: article article_pkey; Type: CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_pkey PRIMARY KEY (id);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: gift_card gift_card_pkey; Type: CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.gift_card
    ADD CONSTRAINT gift_card_pkey PRIMARY KEY (id);


--
-- Name: lexicon lexicon_pkey; Type: CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.lexicon
    ADD CONSTRAINT lexicon_pkey PRIMARY KEY (id);


--
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id);


--
-- Name: reset_password_request reset_password_request_pkey; Type: CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.reset_password_request
    ADD CONSTRAINT reset_password_request_pkey PRIMARY KEY (id);


--
-- Name: therapeutic_exchange therapeutic_exchange_pkey; Type: CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.therapeutic_exchange
    ADD CONSTRAINT therapeutic_exchange_pkey PRIMARY KEY (id);


--
-- Name: treatment treatment_pkey; Type: CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.treatment
    ADD CONSTRAINT treatment_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: idx_23a0e66f675f31b; Type: INDEX; Schema: public; Owner: sandrine
--

CREATE INDEX idx_23a0e66f675f31b ON public.article USING btree (author_id);


--
-- Name: idx_4313acff675f31b; Type: INDEX; Schema: public; Owner: sandrine
--

CREATE INDEX idx_4313acff675f31b ON public.lexicon USING btree (author_id);


--
-- Name: idx_4c49ffcd6b899279; Type: INDEX; Schema: public; Owner: sandrine
--

CREATE INDEX idx_4c49ffcd6b899279 ON public.therapeutic_exchange USING btree (patient_id);


--
-- Name: idx_6d28840dc17ad9a9; Type: INDEX; Schema: public; Owner: sandrine
--

CREATE INDEX idx_6d28840dc17ad9a9 ON public.payment USING btree (payer_id);


--
-- Name: idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750; Type: INDEX; Schema: public; Owner: sandrine
--

CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON public.messenger_messages USING btree (queue_name, available_at, delivered_at, id);


--
-- Name: idx_7ce748aa76ed395; Type: INDEX; Schema: public; Owner: sandrine
--

CREATE INDEX idx_7ce748aa76ed395 ON public.reset_password_request USING btree (user_id);


--
-- Name: idx_e4696a8e471c0366; Type: INDEX; Schema: public; Owner: sandrine
--

CREATE INDEX idx_e4696a8e471c0366 ON public.gift_card USING btree (treatment_id);


--
-- Name: idx_e4696a8eed255ed6; Type: INDEX; Schema: public; Owner: sandrine
--

CREATE INDEX idx_e4696a8eed255ed6 ON public.gift_card USING btree (purchaser_id);


--
-- Name: idx_fe38f844471c0366; Type: INDEX; Schema: public; Owner: sandrine
--

CREATE INDEX idx_fe38f844471c0366 ON public.appointment USING btree (treatment_id);


--
-- Name: idx_fe38f8446b899279; Type: INDEX; Schema: public; Owner: sandrine
--

CREATE INDEX idx_fe38f8446b899279 ON public.appointment USING btree (patient_id);


--
-- Name: uniq_8d93d649e7927c74; Type: INDEX; Schema: public; Owner: sandrine
--

CREATE UNIQUE INDEX uniq_8d93d649e7927c74 ON public."user" USING btree (email);


--
-- Name: article fk_23a0e66f675f31b; Type: FK CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT fk_23a0e66f675f31b FOREIGN KEY (author_id) REFERENCES public."user"(id);


--
-- Name: lexicon fk_4313acff675f31b; Type: FK CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.lexicon
    ADD CONSTRAINT fk_4313acff675f31b FOREIGN KEY (author_id) REFERENCES public."user"(id);


--
-- Name: therapeutic_exchange fk_4c49ffcd6b899279; Type: FK CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.therapeutic_exchange
    ADD CONSTRAINT fk_4c49ffcd6b899279 FOREIGN KEY (patient_id) REFERENCES public."user"(id);


--
-- Name: payment fk_6d28840dc17ad9a9; Type: FK CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fk_6d28840dc17ad9a9 FOREIGN KEY (payer_id) REFERENCES public."user"(id);


--
-- Name: reset_password_request fk_7ce748aa76ed395; Type: FK CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.reset_password_request
    ADD CONSTRAINT fk_7ce748aa76ed395 FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: gift_card fk_e4696a8e471c0366; Type: FK CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.gift_card
    ADD CONSTRAINT fk_e4696a8e471c0366 FOREIGN KEY (treatment_id) REFERENCES public.treatment(id);


--
-- Name: gift_card fk_e4696a8eed255ed6; Type: FK CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.gift_card
    ADD CONSTRAINT fk_e4696a8eed255ed6 FOREIGN KEY (purchaser_id) REFERENCES public."user"(id);


--
-- Name: appointment fk_fe38f844471c0366; Type: FK CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.appointment
    ADD CONSTRAINT fk_fe38f844471c0366 FOREIGN KEY (treatment_id) REFERENCES public.treatment(id);


--
-- Name: appointment fk_fe38f8446b899279; Type: FK CONSTRAINT; Schema: public; Owner: sandrine
--

ALTER TABLE ONLY public.appointment
    ADD CONSTRAINT fk_fe38f8446b899279 FOREIGN KEY (patient_id) REFERENCES public."user"(id);


--
-- PostgreSQL database dump complete
--

\unrestrict TIBdmojoX5r7fybLtgNbVozTi7mzDFlkbHCw7SO2uGEIBbr5W9URLV61LcU6wKJ

